### ISSUE TITLE
Ошибка при установке на win-7 open-server

### ISSUE THREAD

**Issue by yuri25** [chebykinn/uCMS#5]
http://ucms13/sys/install/index.php

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at C:\OpenServer\domains\ucms13\sys\install\index.php:6) in C:\OpenServer\domains\ucms13\sys\install\index.php on line 7

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at C:\OpenServer\domains\ucms13\sys\install\index.php:6) in C:\OpenServer\domains\ucms13\sys\install\index.php on line 7

Warning: Cannot modify header information - headers already sent by (output started at C:\OpenServer\domains\ucms13\sys\install\index.php:6) in C:\OpenServer\domains\ucms13\sys\install\index.php on line 49

**Comment by IVaN4B** [comment]
Установка должна была пройти успешно, но, на серверах с Windows возможны проблемы.

**Comment by IVaN4B** [comment]
Исправлено в 2.0
